import React from 'react';
import { motion } from 'motion/react';
import { Shield, FileText, Scale, Lock, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const TermsOfService: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 px-4 sm:px-6 lg:px-8 transition-colors duration-300">
      <div className="max-w-4xl mx-auto mb-6">
        <button
          onClick={() => navigate(-1)}
          className="inline-flex items-center text-sm font-bold text-gray-500 dark:text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Return to App
        </button>
      </div>
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-4xl mx-auto bg-white dark:bg-gray-800 rounded-3xl shadow-sm border border-gray-100 dark:border-gray-700 overflow-hidden transition-colors duration-300"
      >
        <div className="bg-blue-600 dark:bg-blue-700 p-8 text-white">
          <div className="flex items-center space-x-3 mb-4">
            <Scale className="w-8 h-8" />
            <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
          </div>
          <p className="text-blue-100">Last updated: April 2, 2026</p>
        </div>

        <div className="p-8 prose prose-blue dark:prose-invert max-w-none text-gray-600 dark:text-gray-300 space-y-8">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center">
              <FileText className="w-6 h-6 mr-2 text-blue-600 dark:text-blue-400" />
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing and using PassMate AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. PassMate AI provides an AI-powered study assistant and practice exam platform designed to help users prepare for professional certifications and academic exams.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center">
              <Shield className="w-6 h-6 mr-2 text-blue-600 dark:text-blue-400" />
              2. User Accounts
            </h2>
            <p>
              To access certain features of the Service, you must create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must be at least 13 years old to use this Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center">
              <Lock className="w-6 h-6 mr-2 text-blue-600 dark:text-blue-400" />
              3. Intellectual Property
            </h2>
            <p>
              The Service and its original content, features, and functionality are and will remain the exclusive property of PassMate AI and its licensors. Our AI-generated content is provided for your personal, non-commercial study use. You may not redistribute, sell, or claim ownership of the practice questions or study materials generated by our system.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center">
              <Scale className="w-6 h-6 mr-2 text-blue-600 dark:text-blue-400" />
              4. Subscription and Payments
            </h2>
            <p>
              PassMate AI offers both free and premium subscription tiers. Premium features are billed on a recurring basis. You may cancel your subscription at any time through your profile settings. Refunds are handled on a case-by-case basis in accordance with our refund policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center">
              <FileText className="w-6 h-6 mr-2 text-blue-600 dark:text-blue-400" />
              5. Limitation of Liability
            </h2>
            <p>
              PassMate AI is a study aid. While we strive for accuracy, we do not guarantee that the information provided is error-free or that using the Service will guarantee success in any official examination. We are not liable for any direct or indirect damages resulting from your use of the Service.
            </p>
          </section>

          <section className="bg-gray-50 dark:bg-gray-700/50 p-6 rounded-2xl border border-gray-100 dark:border-gray-600">
            <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">Contact Us</h2>
            <p className="text-sm">
              If you have any questions about these Terms, please contact us at legal@passmate.ai
            </p>
          </section>
        </div>
      </motion.div>
    </div>
  );
};

export default TermsOfService;
